In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
import pandas as pd

In [25]:
data=pd.read_csv("loan_prediction_600.csv")
data.head(5)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,2400000,7475000,12,778,600000,4400000,5675000,2000000,Approved
1,2,0,Not Graduate,Yes,1025000,3050000,8,417,675000,550000,2200000,825000,Rejected
2,3,3,Graduate,No,2275000,7425000,20,506,1775000,1125000,8325000,3200000,Rejected
3,4,3,Graduate,No,2050000,7675000,8,467,4550000,825000,5825000,1975000,Rejected
4,5,5,Not Graduate,Yes,2450000,6050000,20,382,3100000,2050000,7350000,1250000,Rejected

In [4]:
data.shape

(600, 13)

In [5]:
data["self_employed"]=data["self_employed"].map({
    "Yes":1,
    "No":0
})

In [6]:
data["loan_status"]=data["loan_status"].map({
  "Approved":1,
  "Rejected":0  
})

In [7]:
x=data[["self_employed","income_annum","loan_amount","loan_term","cibil_score","residential_assets_value","bank_asset_value"]]
y=data["loan_status"]

In [8]:

x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
x_train

,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,bank_asset_value
145,0,150000,375000,14,543,75000,75000
9,0,275000,1075000,10,388,800000,400000
375,1,325000,1250000,10,755,525000,475000
523,1,1775000,6975000,10,328,2250000,1925000
188,1,1825000,5825000,6,622,1775000,2625000
...,...,...,...,...,...,...,...
71,1,1325000,4650000,4,386,675000,1050000
106,1,2250000,4525000,12,764,150000,2900000
270,0,1300000,3050000,20,513,3350000,1350000
435,0,2100000,5200000,20,590,1275000,2700000
102,1,1075000,3225000,20,618,2850000,600000

In [23]:
y_train.head(5)

145    0
9      0
375    1
523    0
188    1
Name: loan_status, dtype: int64

In [11]:
x_test

,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,bank_asset_value
110,0,75000,275000,8,778,200000,25000
419,1,425000,875000,20,693,550000,425000
565,1,975000,3500000,18,829,1300000,675000
77,0,2250000,8375000,8,801,2900000,2775000
181,1,225000,550000,16,566,25000,150000
...,...,...,...,...,...,...,...
399,0,1775000,5375000,16,610,1450000,2325000
340,0,1700000,5875000,12,341,4825000,2125000
148,1,1225000,2975000,16,709,3650000,950000
494,0,575000,1425000,18,329,1400000,675000
439,1,2375000,5150000,2,731,3350000,2300000

In [12]:
model=RandomForestClassifier(
    n_estimators=10,
    max_depth=3,
    random_state=42
)

In [13]:
print(data.isnull().sum())

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [14]:
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=3, n_estimators=10, random_state=42)

In [15]:
prediction=model.predict(x_test)
prediction

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [16]:
accuracy=accuracy_score(y_test,prediction)
accuracy

0.95

In [17]:
precision=precision_score(y_test,prediction)
precision

0.972972972972973

In [18]:
recall=recall_score(y_test,prediction)
recall

0.9473684210526315

In [ ]:
f1=f1_score(y_test,prediction)
f1

0.96

In [33]:
cm=confusion_matrix(y_test,prediction)
cm

array([[42,  2],
       [ 4, 72]])

In [ ]:
self_employed = input("Self employed (Yes/No): ")
income_annum = float(input("Annual income: "))
loan_amount = float(input("Loan amount: "))
loan_term = float(input("Loan term: "))
cibil_score = float(input("CIBIL score: "))
residential_assets_value = float(input("Residential assets value: "))
bank_asset_value = float(input("Bank asset value: "))

self_employed= 1 if self_employed.lower()=="yes" else 0


new_data=pd.DataFrame({
    "self_employed":[self_employed],
    "income_annum":[income_annum],
    "loan_amount":[loan_amount],
    "loan_term":[loan_term],
    "cibil_score":[cibil_score],
    "residential_assets_value":[residential_assets_value],
    "bank_asset_value":[bank_asset_value]
})

new_prediction=model.predict(new_data)
if new_prediction[0]==1:
    print("Loan Approved")
else:
    print("Loan Rejected")
print(new_prediction[0])

Please enter Yes or No

ValueError: could not convert string to float: 'w'

In [41]:
import joblib

joblib.dump(model,"loan_prediction.pkl")

['loan_prediction.pkl']